# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65dbc15ab02c53c5738f87bbaa7a933d0fca68f5f01b577fa6869b401e193f725eca0eb1960f096453cf70b4b9e745cf049e8f7f63ccbf3980975bb733d34555

test:
  secret_key_base: 5a860d42c092b62f23106fb34ec9bf4a30f80228810118134a26a6c7b798de356fcb782792ddc1597d951a3b49e83b2cb8d8e0758ad50d75b5730603d2be469b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
